### ISSUE TITLE
Correct Gem Versions?

### ISSUE THREAD

**Issue by cjcheshire** [juliocesar/rack-pagespeed#32]
I'm still new to all this but I get:

Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rack-pagespeed depends on
      rack (= 1.2.1)

```
sinatra (~> 1.2.6) depends on
  rack (1.3.2)
```

I thought I had all the latest versions?

**Comment by juliocesar** [comment]
Yep, I'll be working on rack-pagespeed in the next few days. Expect a release soon that addresses that among other issues.

Thanks for reporting!

**Comment by juliocesar** [comment]
Fixed. Run `gem install` again, and make sure you're getting version `1.1.0`.

**Comment by cjcheshire** [comment]
Thanks for the prompt update!  I'm still getting a boot error with "Gem::LoadError: Unable to activate rack-pagespeed-1.0.9, because rack-1.3.2 conflicts with rack (= 1.2.1)".

Shotgun reported "Invalid gemspec in [/Users/Chris/.rvm/gems/ree-1.8.7-2011.03@wfp/specifications/rack-pagespeed-1.1.0.gemspec]: invalid date format in specification: "2011-08-09 00:00:00.000000000Z""

Sorry to be a pain!

**Comment by juliocesar** [comment]
That's a weird one. What are you using it with? Sinatra? Rails? And what version of it?

I appreciate the reports, so no worries, keep them coming!

**Comment by cjcheshire** [comment]
Cool, thanks. 

I'm using Sinatra.  Here is the dump from gem list:

---

**\* LOCAL GEMS ***

Invalid gemspec in [/Users/Chris/.rvm/gems/ree-1.8.7-2011.03@wfp/specifications/rack-pagespeed-1.1.0.gemspec]: invalid date format in specification: "2011-08-09 00:00:00.000000000Z"
activerecord (2.2.3)
activesupport (2.2.3)
addressable (2.2.6)
aws-s3 (0.6.2)
builder (3.0.0)
bundle (0.0.1)
bundler (1.0.15)
dalli (1.0.5)
haml (3.1.2)
heroku (2.4.0)
i18n (0.6.0)
jsmin (1.0.1)
launchy (2.0.5)
mail (2.3.0)
memcached (1.3, 1.0.2)
mime-types (1.16)
nokogiri (1.5.0, 1.4.4)
polyglot (0.3.2)
pony (1.3)
rack (1.3.2, 1.2.1)
rack-pagespeed (1.0.9)
rake (0.8.7)
ratpack (0.1.3)
rest-client (1.6.3)
sequel (3.20.0)
shotgun (0.9)
sinatra (1.2.6, 1.0)
sinatra-activerecord (0.1.3)
sinatra-content-for (0.2)
sqlite3 (1.3.4)
sqlite3-ruby (1.3.3)
taps (0.3.23)
term-ansicolor (1.0.6)
tilt (1.3.2)
treetop (1.4.10)
will_paginate (2.3.16, 2.3.15)
xml-simple (1.1.0)

---

My gem file includes:

source 'http://rubygems.org'

gem 'sinatra', '~>1.2.6'
gem 'haml', '~>3.1.2'
gem 'sqlite3', '~>1.3.3'
gem 'activerecord', '~>2.2.3'
gem 'will_paginate', '~>2.3.15'
gem 'aws-s3', '~>0.6.2'
gem 'sinatra-content-for', '~>0.2'
gem 'pony', '~>1.3'
gem 'ratpack', '~>0.1.3'
gem 'sinatra-activerecord'
gem 'builder'
gem 'rack-pagespeed', '~>1.1.0'

**Comment by juliocesar** [comment]
About the first part of your report

```
Thanks for the prompt update! I'm still getting a boot error with "Gem::LoadError: Unable to activate rack-pagespeed-1.0.9, 
because rack-1.3.2 conflicts with rack (= 1.2.1)".
```

Looks like you might have a `Gemfile.lock` file perhaps lost somewhere still referring to rack-pagespeed 1.0.9. Make sure that whatever references you have to it are gone.

As for the second part:

```
Shotgun reported "Invalid gemspec in [/Users/Chris/.rvm/gems/ree-1.8.7-2011.03@wfp/specifications/rack-pagespeed-
1.1.0.gemspec]: invalid date format in specification: "2011-08-09 00:00:00.000000000Z""
```

I found [this link](http://help.rubygems.org/discussions/problems/575-invalid-gemspec-with-invalid-date-format-in-specification), which seems to be the case really. I did build this gemspec on Ruby 1.9.2. Apparently if you upgrade rubygems on your side of the equation, it should work.

**Comment by cjcheshire** [comment]
Hey.  I checked my gemfile.lock, it only references the new version.

I've done a ruby gems update but I'm wondering if trying to move to 1.9.2 might be the answer as doing a bundle update now generates

```WARNING:  #<ArgumentError: Illformed requirement ["#<YAML::Syck::DefaultKey:0x10ed75488> 2.6.0"]>

# -_\- encoding: utf-8 -_-

Gem::Specification.new do |s|
  s.name = %q{rack-pagespeed}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julio Cesar Ody"]
  s.date = %q{2011-08-09 00:00:00.000000000Z}
  s.description = %q{Web page speed optimizations at the Rack level}
  s.email = %q{julio@awesomebydesign.com}
  s.extra_rdoc_files = ["README.md"]
  s.files = ["Gemfile", "README.md", "Rakefile", "VERSION", "lib/rack-pagespeed.rb", "lib/rack/pagespeed.rb", "lib/rack/pagespeed/config.rb", "lib/rack/pagespeed/filters/all.rb", "lib/rack/pagespeed/filters/base.rb", "lib/rack/pagespeed/filters/combine_css.rb", "lib/rack/pagespeed/filters/combine_javascripts.rb", "lib/rack/pagespeed/filters/inline_css.rb", "lib/rack/pagespeed/filters/inline_images.rb", "lib/rack/pagespeed/filters/inline_javascripts.rb", "lib/rack/pagespeed/filters/minify_javascripts.rb", "lib/rack/pagespeed/store/disk.rb", "lib/rack/pagespeed/store/memcached.rb", "lib/rack/pagespeed/store/redis.rb", "rack-pagespeed.gemspec", "spec/config_spec.rb", "spec/filters/combine_css_spec.rb", "spec/filters/combine_javascripts_spec.rb", "spec/filters/filter_spec.rb", "spec/filters/inline_css_spec.rb", "spec/filters/inline_images_spec.rb", "spec/filters/inline_javascript_spec.rb", "spec/filters/minify_javascript_spec.rb", "spec/fixtures/all-small-dog-breeds.jpg", "spec/fixtures/complex.html", "spec/fixtures/foo.js", "spec/fixtures/hh-reset.css", "spec/fixtures/huge.css", "spec/fixtures/iphone.css", "spec/fixtures/jquery-1.4.1.min.js", "spec/fixtures/medialess1.css", "spec/fixtures/medialess2.css", "spec/fixtures/mock_store.rb", "spec/fixtures/mylib.js", "spec/fixtures/noexternalcss.html", "spec/fixtures/noscripts.html", "spec/fixtures/ohno.js", "spec/fixtures/reset.css", "spec/fixtures/screen.css", "spec/fixtures/styles.html", "spec/pagespeed_spec.rb", "spec/spec_helper.rb", "spec/store/disk_spec.rb", "spec/store/memcached_spec.rb", "spec/store/redis_spec.rb"]
  s.homepage = %q{http://github.com/juliocesar/rack-pagespeed}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Web page speed optimizations at the Rack level}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

```
if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
  s.add_runtime_dependency(%q<rack>, [">= 0"])
  s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
  s.add_runtime_dependency(%q<jsmin>, [">= 0"])
  s.add_runtime_dependency(%q<dalli>, [">= 0"])
  s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
  s.add_runtime_dependency(%q<rack>, [">= 0"])
  s.add_runtime_dependency(%q<memcached>, [">= 0"])
  s.add_runtime_dependency(%q<mime-types>, [">= 0"])
  s.add_runtime_dependency(%q<jsmin>, [">= 0"])
  s.add_development_dependency(%q<rspec>, ["#<YAML::Syck::DefaultKey:0x10ed75488> 2.6.0"])
  s.add_development_dependency(%q<capybara>, ["#<YAML::Syck::DefaultKey:0x10ed713d8> 1.1.0"])
else
  s.add_dependency(%q<rack>, [">= 0"])
  s.add_dependency(%q<nokogiri>, [">= 0"])
  s.add_dependency(%q<jsmin>, [">= 0"])
  s.add_dependency(%q<dalli>, [">= 0"])
  s.add_dependency(%q<nokogiri>, [">= 0"])
  s.add_dependency(%q<rack>, [">= 0"])
  s.add_dependency(%q<memcached>, [">= 0"])
  s.add_dependency(%q<mime-types>, [">= 0"])
  s.add_dependency(%q<jsmin>, [">= 0"])
  s.add_dependency(%q<rspec>, ["#<YAML::Syck::DefaultKey:0x10ed75488> 2.6.0"])
  s.add_dependency(%q<capybara>, ["#<YAML::Syck::DefaultKey:0x10ed713d8> 1.1.0"])
end
```

  else
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<jsmin>, [">= 0"])
    s.add_dependency(%q<dalli>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<memcached>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 0"])
    s.add_dependency(%q<jsmin>, [">= 0"])
    s.add_dependency(%q<rspec>, ["#YAML::Syck::DefaultKey:0x10ed75488 2.6.0"])
    s.add_dependency(%q<capybara>, ["#YAML::Syck::DefaultKey:0x10ed713d8 1.1.0"])
  end
end
WARNING:  Invalid .gemspec format in '/Users/Chris/.rvm/gems/ree-1.8.7-2011.03@wfp/specifications/rack-pagespeed-1.1.0.gemspec'```

**Comment by cjcheshire** [comment]
I did a cleanup to remove the older version too.  I'll investigate how easy it will be to upgrade to 1.9.2 (I'm more a front end guy dabbling with rails for work).
